;; -*- lexical-binding: t -*-

(require 'Emil/Env)

(defvar-local Emil:Package:author-mode-timer nil)

(defvar-local Emil:Package:author-mode-previous-symbol nil)

(define-minor-mode Emil:Package:author-mode
  "Not documented"
  :group 'emacs
  (cond
   (Emil:Package:author-mode
    (setq Emil:Package:author-mode-timer
          (run-with-idle-timer eldoc-idle-delay t #'Emil:Package:author-mode-display)))
   ((timerp Emil:Package:author-mode-timer)
    (cancel-timer Emil:Package:author-mode-timer))))

(defun Emil:Package:author-mode-display ()
  (when Emil:Package:author-mode
    (when-let (symbol (ignore-errors
                        (save-excursion
                          (back-to-indentation)
                          (forward-char 1)
                          (symbol-at-point))))
      (when (and (fboundp symbol)
                 (not (eq symbol Emil:Package:author-mode-previous-symbol)))
        (setq Emil:Package:author-mode-previous-symbol symbol)
        (let ((help-window-select nil))
          (describe-function symbol))))))

(Emil:Env:declare-functions
  (% . (-> (number-or-marker number-or-marker) integer))
  (* . (-> (&rest number-or-marker) number))
  (+ . (-> (&rest number-or-marker) number))
  (- . (-> (&optional number-or-marker &rest number-or-marker) number))
  (/ . (-> (number-or-marker &rest number-or-marker) number))
  (/= . (-> (number-or-marker number-or-marker) boolean))
  (< . (-> (number-or-marker &rest number-or-marker) boolean))
  (<= . (-> (number-or-marker &rest number-or-marker) boolean))
  (= . (-> (number-or-marker &rest number-or-marker) boolean))
  (> . (-> (number-or-marker &rest number-or-marker) boolean))
  (>= . (-> (number-or-marker &rest number-or-marker) boolean))
  (1+ . (-> (number-or-marker) number))
  (1- . (-> (number-or-marker) number))
  (abort-minibuffers . (-> () Void))
  (abort-recursive-edit . (-> () Void))
  (abs . (-> (number) number))
  (accept-process-output . (-> (&optional process number number Any) Void))
  (access-file . (-> (string string) Null))
  (accessible-keymaps . (-> (list &optional Any) list))
  (acos . (-> (number) number))
  (active-minibuffer-window . (-> () window))
  (add-face-text-property . (-> (integer integer Any &optional boolean Any) Void))
  (add-name-to-file . (-> (string string &optional Any) Void))
  (add-text-properties . (-> (integer integer list &optional Any) boolean))
  (add-variable-watcher . (-> (symbol (-> (symbol Any symbol buffer) Void)) Void))
  (all-completions . (-> (string Any &optional (-> (Any) boolean)) (List string)))
  (all-threads . (-> () (List thread)))
  (and . (-> (&rest Any) Any))
  (android-browse-url . (-> (&rest Any) Any))
  (android-clipboard-exists-p . (-> (&rest Any) Any))
  (android-clipboard-owner-p . (-> (&rest Any) Any))
  (android-detect-mouse . (-> (&rest Any) Any))
  (android-display-monitor-attributes-list . (-> (&rest Any) Any))
  (android-enumerate-fonts . (-> (&rest Any) Any))
  (android-external-storage-available-p . (-> (&rest Any) Any))
  (android-frame-edges . (-> (&rest Any) Any))
  (android-frame-geometry . (-> (&rest Any) Any))
  (android-frame-list-z-order . (-> (&rest Any) Any))
  (android-frame-restack . (-> (&rest Any) Any))
  (android-get-clipboard . (-> (&rest Any) Any))
  (android-get-clipboard-data . (-> (&rest Any) Any))
  (android-get-clipboard-targets . (-> (&rest Any) Any))
  (android-get-connection . (-> (&rest Any) Any))
  (android-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (android-notifications-notify . (-> (&rest Any) Any))
  (android-query-battery . (-> (&rest Any) Any))
  (android-request-directory-access . (-> (&rest Any) Any))
  (android-request-storage-access . (-> (&rest Any) Any))
  (android-set-clipboard . (-> (&rest Any) Any))
  (android-set-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (android-toggle-on-screen-keyboard . (-> (&rest Any) Any))
  (append . (-> (&rest (Sequence 'a)) (List 'a)))
  (apply . (-> ((-> (&rest Any) 'a) &rest Any) 'a))
  (aref . (-> ((Array 'a) integer) 'a))
  (arrayp . (-> (Any) boolean))
  (aset . (-> ((Array 'a) integer 'a) 'a))
  (ash . (-> (integer integer) integer))
  (asin . (-> (number) number))
  (assoc . (-> ('a (List (Cons 'a 'b)) &optional (-> ('a 'a) boolean)) (Cons 'a 'b)))
  (assoc-string . (-> (Any list &optional boolean) Any))
  (assq . (-> ('a (List (Cons 'a 'b))) (Cons 'a 'b)))
  (atan . (-> (number &optional number) number))
  (atom . (-> (Any) boolean))
  (autoload . (-> (symbol string &optional string Any symbol) Void))
  (autoload-do-load . (-> (list &optional symbol boolean) Any))
  (backtrace-debug . (-> (integer boolean) Void))
  (backtrace-eval . (-> (Any integer integer) Any))
  (backtrace-frame--internal . (-> (function integer integer) Any))
  (backtrace--frames-from-thread . (-> (thread) Any))
  (backtrace--locals . (-> (integer &optional integer) (List (Cons symbol Any))))
  (backward-char . (-> (&optional integer) Void))
  (backward-prefix-chars . (-> () Void))
  (bare-symbol . (-> (symbol) symbol))
  (bare-symbol-p . (-> (Any) boolean))
  (barf-if-buffer-read-only . (-> (&optional integer) Void))
  (base64-decode-region . (-> (integer integer &optional boolean boolean) Void))
  (base64-decode-string . (-> (string &optional boolean boolean) string))
  (base64-encode-region . (-> (integer integer &optional boolean) Void))
  (base64-encode-string . (-> (string &optional boolean) string))
  (base64url-encode-region . (-> (integer integer &optional boolean) integer))
  (base64url-encode-string . (-> (integer integer &optional boolean) integer))
  (beginning-of-line . (-> (&optional integer) Void))
  (bidi-find-overridden-directionality . (-> (integer integer Any &optional symbol) integer))
  (bidi-resolved-levels . (-> (&optional integer) array))
  (bitmap-spec-p . (-> (Any) boolean))
  (bobp . (-> () boolean))
  (bolp . (-> () boolean))
  (bool-vector . (-> (&rest Any) bool-vector))
  (bool-vector-count-consecutive . (-> (bool-vector boolean integer) integer))
  (bool-vector-count-population . (-> (bool-vector) integer))
  (bool-vector-exclusive-or . (-> (bool-vector bool-vector &optional bool-vector) bool-vector))
  (bool-vector-intersection . (-> (bool-vector bool-vector &optional bool-vector) bool-vector))
  (bool-vector-not . (-> (bool-vector &optional bool-vector) bool-vector))
  (bool-vector-p . (-> (Any) boolean))
  (bool-vector-set-difference . (-> (bool-vector bool-vector &optional bool-vector) bool-vector))
  (bool-vector-subsetp . (-> (bool-vector bool-vector) boolean))
  (bool-vector-union . (-> (bool-vector bool-vector &optional bool-vector) bool-vector))
  (boundp . (-> (symbol) boolean))
  (buffer-base-buffer . (-> (&optional buffer) buffer))
  (buffer-chars-modified-tick . (-> (&optional buffer) integer))
  (buffer-enable-undo . (-> (&optional buffer) Void))
  (buffer-file-name . (-> (&optional buffer) string))
  (buffer-hash . (-> (&optional buffer) string))
  (buffer-line-statistics . (-> (&optional buffer) (List number)))
  (buffer-list . (-> (&optional frame) (List buffer)))
  (buffer-live-p . (-> (Any) boolean))
  (buffer-local-value . (-> (symbol buffer) Any))
  (buffer-local-variables . (-> (&optional buffer) (List (Cons symbol Any))))
  (buffer-modified-p . (-> (&optional buffer) boolean))
  (buffer-modified-tick . (-> (&optional buffer) integer))
  (buffer-name . (-> (&optional buffer) string))
  (bufferp . (-> (Any) boolean))
  (buffer-size . (-> (&optional buffer) integer))
  (buffer-string . (-> () string))
  (buffer-substring . (-> (integer integer) string))
  (buffer-substring-no-properties . (-> (integer integer) string))
  (buffer-swap-text . (-> (buffer) Void))
  (buffer-text-pixel-size . (-> (&optional Any window number number) Any))
  (bury-buffer-internal . (-> (buffer) Void))
  (byte-code . (-> (string vector integer) Any))
  (byte-code-function-p . (-> (Any) boolean))
  (byteorder . (-> () integer))
  (byte-to-position . (-> (integer) integer))
  (byte-to-string . (-> (integer) string))
  (call-interactively . (-> (function boolean vector) Void))
  (call-last-kbd-macro . (-> (&optional Any function) Void))
  (call-process . (-> (string &optional string Any boolean &rest string) integer))
  (call-process-region . (-> (integer integer &optional boolean Any boolean &rest string) integer))
  (cancel-kbd-macro-events . (-> () Void))
  (capitalize . (-> (Any) Any))
  (capitalize-region . (-> (integer integer &optional boolean) Void))
  (capitalize-word . (-> (&optional integer) Void))
  (car . (-> ((Cons 'a 'b)) 'a))
  (car-less-than-car . (-> ((Cons number Any) (Cons number Any)) boolean))
  (car-safe . (-> ((Cons 'a 'b)) 'a))
  (case-table-p . (-> (Any) boolean))
  (category-docstring . (-> (number &optional char-table) string))
  (category-set-mnemonics . (-> (bool-vector) string))
  (category-table . (-> () char-table))
  (category-table-p . (-> (Any) boolean))
  (ccl-execute . (-> (&rest Any) Any))
  (ccl-execute-on-string . (-> (&rest Any) Any))
  (ccl-program-p . (-> (&rest Any) Any))
  (cdr . (-> ((Cons 'a 'b)) 'b))
  (cdr-safe . (-> ((Cons 'a 'b)) 'b))
  (ceiling . (-> (number &optional number) number))
  (characterp . (-> (Any) boolean))
  (char-after . (-> (&optional integer) integer))
  (char-before . (-> (&optional integer) integer))
  (char-category-set . (-> (integer) bool-vector))
  (char-charset . (-> (integer &optional boolean) symbol))
  (char-equal . (-> (integer integer) boolean))
  (char-or-string-p . (-> (Any) boolean))
  (char-resolve-modifiers . (-> (integer) integer))
  (charset-after . (-> (&optional integer) symbol))
  (charset-id-internal . (-> (&optional symbol) integer))
  (charsetp . (-> (Any) boolean))
  (charset-plist . (-> (symbol) list))
  (charset-priority-list . (-> (&optional boolean) (List symbol)))
  (char-syntax . (-> (integer) integer))
  (char-table-extra-slot . (-> (char-table integer) Any))
  (char-table-p . (-> (Any) boolean))
  (char-table-parent . (-> (char-table) char-table))
  (char-table-range . (-> (char-table Any) Any))
  (char-table-subtype . (-> (char-table) symbol))
  (char-to-string . (-> (integer) string))
  (char-width . (-> (integer) integer))
  (check-coding-system . (-> (Any) Any))
  (check-coding-systems-region . (-> (&rest Any) Any))
  (clear-buffer-auto-save-failure . (-> (&rest Any) Any))
  (clear-charset-maps . (-> () Void))
  (clear-composition-cache . (-> () Void))
  (clear-face-cache . (-> (&optional boolean) Void))
  (clear-font-cache . (-> () Void))
  (clear-image-cache . (-> (&optional Any boolean) Void))
  (clear-string . (-> (string) Void))
  (clear-this-command-keys . (-> (&optional boolean) Void))
  (close-font . (-> (font-object &optional frame) Void))
  (clrhash . (-> (hash-table) hash-table))
  (coding-system-aliases . (-> (symbol) (List symbol)))
  (coding-system-base . (-> (symbol) symbol))
  (coding-system-eol-type . (-> (symbol) Any))
  (coding-system-p . (-> (Any) boolean))
  (coding-system-plist . (-> (symbol) list))
  (coding-system-priority-list . (-> (&optional boolean) (List symbol)))
  (coding-system-put . (-> (symbol symbol Any) Any))
  (color-distance . (-> (Any Any &optional frame (-> ((List integer) (List integer)) integer)) Any))
  (color-gray-p . (-> (string &optional frame) boolean))
  (color-supported-p . (-> (string &optional frame boolean) boolean))
  (color-values-from-color-spec . (-> (string) (List integer)))
  (combine-after-change-execute . (-> () Void))
  (command-error-default-function . (-> (&rest Any) Any))
  (command-modes . (-> (symbol) (List symbol)))
  (commandp . (-> (Any &optional boolean) boolean))
  (command-remapping . (-> (symbol &optional list Any) Any))
  (compare-buffer-substrings . (-> (buffer integer integer buffer integer integer) integer))
  (compare-strings . (-> (string integer integer string integer integer &optional boolean) Any))
  (comp--compile-ctxt-to-file . (-> (string) Void))
  (comp-el-to-eln-filename . (-> (string &optional string) string))
  (comp-el-to-eln-rel-filename . (-> (string) string))
  (comp--init-ctxt . (-> () boolean))
  (comp--install-trampoline . (-> (symbol Any) Void))
  (comp--late-register-subr . (-> (&rest Any) Any))
  (completing-read . (-> (string Any &optional (-> (Any) boolean) Any Any Any Any boolean) string))
  (comp-libgccjit-version . (-> () (List integer)))
  (comp-native-compiler-options-effective-p . (-> () boolean))
  (comp-native-driver-options-effective-p . (-> () boolean))
  (compose-region-internal . (-> (&rest Any) Any))
  (compose-string-internal . (-> (&rest Any) Any))
  (composition-get-gstring . (-> (&rest Any) Any))
  (composition-sort-rules . (-> (&rest Any) Any))
  (comp--register-lambda . (-> (&rest Any) Any))
  (comp--register-subr . (-> (&rest Any) Any))
  (comp--release-ctxt . (-> (&rest Any) Any))
  (comp--subr-signature . (-> (&rest Any) Any))
  (compute-motion . (-> (&rest Any) Any))
  (concat . (-> (&rest (Sequence integer)) string))
  (condition-mutex . (-> (condvar) mutex))
  (condition-name . (-> (condvar) string))
  (condition-notify . (-> (condvar &optional boolean) Void))
  (condition-variable-p . (-> (Any) boolean))
  (condition-wait . (-> (condvar) Void))
  (cons . (-> ('a 'b) (Cons 'a 'b)))
  (consp . (-> (Any) boolean))
  (constrain-to-field . (-> (integer integer &optional boolean boolean boolean) integer))
  (continue-process . (-> (&optional Any symbol) Void))
  (controlling-tty-p . (-> (&optional Any) boolean))
  (coordinates-in-window-p . (-> ((Cons integer integer)) Any))
  (copy-alist . (-> ((List 'a)) (List 'a)))
  (copy-category-table . (-> (&optional char-table) char-table))
  (copy-file . (-> (string string Any boolean boolean boolean) Void))
  (copy-hash-table . (-> (hash-table) hash-table))
  (copy-keymap . (-> (list) list))
  (copy-marker . (-> (&optional number-or-marker boolean) marker))
  (copy-sequence . (-> ((Sequence 'a)) (Sequence 'a)))
  (copysign . (-> (float float) float))
  (copy-syntax-table . (-> (&optional char-table) char-table))
  (cos . (-> (number) number))
  (current-active-maps . (-> (&optional boolean list) Any))
  (current-bidi-paragraph-direction . (-> (&optional buffer) symbol))
  (current-buffer . (-> () buffer))
  (current-case-table . (-> () char-table))
  (current-column . (-> () integer))
  (current-cpu-time . (-> () (Cons integer integer)))
  (current-global-map . (-> () list))
  (current-idle-time . (-> () (List integer)))
  (current-indentation . (-> () integer))
  (current-input-mode . (-> () list))
  (current-local-map . (-> () list))
  (current-message . (-> () string))
  (current-minor-mode-maps . (-> () list))
  (current-thread . (-> () thread))
  (current-time . (-> () (List integer)))
  (current-time-string . (-> (&optional Any Any) string))
  (current-time-zone . (-> (&optional Any Any) list))
  (current-window-configuration . (-> (&optional frame) window-configuration))
  (cygwin-convert-file-name-from-windows . (-> (&rest Any) Any))
  (cygwin-convert-file-name-to-windows . (-> (&rest Any) Any))
  (daemon-initialized . (-> () Void))
  (daemonp . (-> () Any))
  (dbus-get-unique-name . (-> (Any) string))
  (dbus--init-bus . (-> (Any boolean) Void))
  (dbus-message-internal . (-> (&rest Any) Any))
  (debug-timer-check . (-> (&rest Any) Any))
  (declare-equiv-charset . (-> (Any Any Any Any) Void))
  (decode-big5-char . (-> (integer) integer))
  (decode-char . (-> (symbol integer) integer))
  (decode-coding-region . (-> (integer integer symbol &optional Any) Any))
  (decode-coding-string . (-> (string symbol &optional boolean buffer) Any))
  (decode-sjis-char . (-> (integer) integer))
  (decode-time . (-> (&optional Any Any symbol) list))
  (defalias . (-> (symbol Any &optional string) Void))
  (default-boundp . (-> (symbol) boolean))
  (default-file-modes . (-> () integer))
  (default-printer-name . (-> (&rest Any) Any))
  (default-toplevel-value . (-> (symbol) Any))
  (default-value . (-> (symbol) Any))
  (defconst-1 . (-> (symbol Any &optional string) symbol))
  (define-category . (-> (integer string &optional char-table) Void))
  (define-charset-alias . (-> (symbol symbol) Void))
  (define-charset-internal . (-> (&rest Any) Any))
  (define-coding-system-alias . (-> (symbol symbol) Void))
  (define-coding-system-internal . (-> (&rest Any) Any))
  (define-fringe-bitmap . (-> (symbol (Array integer) &optional integer integer Any) symbol))
  (define-hash-table-test . (-> (symbol (-> (Any Any) boolean) (-> (Any) Any)) Void))
  (define-key . (-> (list Any Any &optional boolean) Void))
  (defvar-1 . (-> (symbol Any &optional string) symbol))
  (defvaralias . (-> (symbol symbol &optional string) symbol))
  (delete . (-> ('a (Sequence 'a)) (Sequence 'a)))
  (delete-all-overlays . (-> (&optional buffer) Void))
  (delete-and-extract-region . (-> (integer integer) string))
  (delete-char . (-> (integer &optional boolean) Void))
  (delete-directory-internal . (-> (string) Void))
  (delete-field . (-> (&optional integer) Void))
  (delete-file-internal . (-> (&rest Any) Any))
  (delete-frame . (-> (&optional frame boolean) Void))
  (delete-other-windows-internal . (-> (&optional window window) Void))
  (delete-overlay . (-> (overlay) Void))
  (delete-process . (-> (&optional process) Void))
  (delete-region . (-> (integer integer) Void))
  (delete-terminal . (-> (&optional terminal boolean) Void))
  (delete-window-internal . (-> (window) Void))
  (delete-xwidget-view . (-> (&rest Any) Any))
  (delq . (-> ('a (List 'a)) (List 'a)))
  (describe-buffer-bindings . (-> (buffer &optional Any boolean) Void))
  (describe-vector . (-> (vector &optional (-> (Any) Void)) Void))
  (destroy-fringe-bitmap . (-> (symbol) Void))
  (detect-coding-region . (-> (integer integer &optional boolean) symbol))
  (detect-coding-string . (-> (string &optional boolean) symbol))
  (ding . (-> (&optional boolean) Void))
  (directory-file-name . (-> (string) string))
  (directory-files . (-> (string &optional boolean boolean boolean integer) (List string)))
  (directory-files-and-attributes . (-> (string &optional boolean boolean boolean integer)
                                        (List (Cons string list))))
  (directory-name-p . (-> (string) boolean))
  (discard-input . (-> () Void))
  (display--line-is-continued-p . (-> () boolean))
  (display-supports-face-attributes-p . (-> (Any &optional Any) boolean))
  (display--update-for-mouse-movement . (-> (integer integer) Void))
  (do-auto-save . (-> (&optional boolean boolean) Void))
  (documentation . (-> (symbol &optional boolean) string))
  (documentation-property . (-> (symbol symbol &optional boolean) string))
  (downcase . (-> (Any) Any))
  (downcase-region . (-> (integer integer &optional boolean) Void))
  (downcase-word . (-> (integer) Void))
  (draw-string . (-> (&rest Any) Any))
  (dump-colors . (-> (&rest Any) Any))
  (dump-emacs . (-> (&rest Any) Any))
  (dump-emacs-portable . (-> (string &optional boolean) Void))
  (dump-emacs-portable--sort-predicate . (-> (Any Any) Any))
  (dump-emacs-portable--sort-predicate-copied . (-> (&rest Any) Any))
  (dump-face . (-> (&rest Any) Any))
  (dump-frame-glyph-matrix . (-> (&rest Any) Any))
  (dump-glyph-matrix . (-> (&rest Any) Any))
  (dump-glyph-row . (-> (&rest Any) Any))
  (dump-redisplay-history . (-> (&rest Any) Any))
  (dump-tab-bar-row . (-> (&rest Any) Any))
  (dump-tool-bar-row . (-> (&rest Any) Any))
  (elt . (-> ((Sequence 'a) integer) 'a))
  (emacs-pid . (-> () integer))
  (encode-big5-char . (-> (integer) integer))
  (encode-char . (-> (integer symbol) integer))
  (encode-coding-region . (-> (integer integer symbol &optional Any) Any))
  (encode-coding-string . (-> (string symbol &optional boolean buffer) Any))
  (encode-sjis-char . (-> (integer) integer))
  (encode-time . (-> (list) list))
  (end-kbd-macro . (-> (&optional boolean (-> () boolean)) Void))
  (end-of-line . (-> (&optional integer) Void))
  (eobp . (-> () boolean))
  (eolp . (-> () boolean))
  (eq . (-> (Any Any) boolean))
  (eql . (-> (Any Any) boolean))
  (equal . (-> (Any Any) boolean))
  (equal-including-properties . (-> (Any Any) boolean))
  (erase-buffer . (-> () Void))
  (error-message-string . (-> ((Cons symbol Any)) string))
  (eval . (-> (Any &optional Any) Any))
  (eval-buffer . (-> (&rest Any) Any))
  (eval-region . (-> (&rest Any) Any))
  (event-convert-list . (-> (&rest Any) Any))
  (execute-kbd-macro . (-> (&rest Any) Any))
  (exit-recursive-edit . (-> (&rest Any) Any))
  (exp . (-> (&rest Any) Any))
  (expand-file-name . (-> (&rest Any) Any))
  (expt . (-> (&rest Any) Any))
  (external-debugging-output . (-> (&rest Any) Any))
  (face-attribute-relative-p . (-> (&rest Any) Any))
  (face-attributes-as-vector . (-> (&rest Any) Any))
  (face-font . (-> (&rest Any) Any))
  (fboundp . (-> (&rest Any) Any))
  (fceiling . (-> (&rest Any) Any))
  (featurep . (-> (&rest Any) Any))
  (fetch-bytecode . (-> (&rest Any) Any))
  (ffloor . (-> (&rest Any) Any))
  (field-beginning . (-> (&rest Any) Any))
  (field-end . (-> (&rest Any) Any))
  (field-string . (-> (&rest Any) Any))
  (field-string-no-properties . (-> (&rest Any) Any))
  (file-accessible-directory-p . (-> (&rest Any) Any))
  (file-acl . (-> (&rest Any) Any))
  (file-attributes . (-> (&rest Any) Any))
  (file-attributes-lessp . (-> (&rest Any) Any))
  (file-directory-p . (-> (&rest Any) Any))
  (file-executable-p . (-> (&rest Any) Any))
  (file-exists-p . (-> (&rest Any) Any))
  (file-locked-p . (-> (&rest Any) Any))
  (file-modes . (-> (&rest Any) Any))
  (file-name-absolute-p . (-> (&rest Any) Any))
  (file-name-all-completions . (-> (&rest Any) Any))
  (file-name-as-directory . (-> (&rest Any) Any))
  (file-name-case-insensitive-p . (-> (&rest Any) Any))
  (file-name-completion . (-> (&rest Any) Any))
  (file-name-concat . (-> (&rest Any) Any))
  (file-name-directory . (-> (&rest Any) Any))
  (file-name-nondirectory . (-> (&rest Any) Any))
  (file-newer-than-file-p . (-> (&rest Any) Any))
  (file-readable-p . (-> (&rest Any) Any))
  (file-regular-p . (-> (&rest Any) Any))
  (file-selinux-context . (-> (&rest Any) Any))
  (file-symlink-p . (-> (&rest Any) Any))
  (file-system-info . (-> (&rest Any) Any))
  (file-writable-p . (-> (&rest Any) Any))
  (fillarray . (-> (&rest Any) Any))
  (find-buffer . (-> (&rest Any) Any))
  (find-charset-region . (-> (&rest Any) Any))
  (find-charset-string . (-> (&rest Any) Any))
  (find-coding-systems-region-internal . (-> (&rest Any) Any))
  (find-composition-internal . (-> (&rest Any) Any))
  (find-file-name-handler . (-> (&rest Any) Any))
  (find-font . (-> (&rest Any) Any))
  (find-operation-coding-system . (-> (&rest Any) Any))
  (float . (-> (&rest Any) Any))
  (floatp . (-> (&rest Any) Any))
  (float-time . (-> (&rest Any) Any))
  (floor . (-> (&rest Any) Any))
  (flush-standard-output . (-> (&rest Any) Any))
  (fmakunbound . (-> (&rest Any) Any))
  (following-char . (-> (&rest Any) Any))
  (font-at . (-> (&rest Any) Any))
  (font-drive-otf . (-> (&rest Any) Any))
  (font-face-attributes . (-> (&rest Any) Any))
  (font-family-list . (-> (&rest Any) Any))
  (font-get . (-> (&rest Any) Any))
  (font-get-glyphs . (-> (&rest Any) Any))
  (font-get-system-font . (-> (&rest Any) Any))
  (font-get-system-normal-font . (-> (&rest Any) Any))
  (font-has-char-p . (-> (&rest Any) Any))
  (font-info . (-> (&rest Any) Any))
  (font-match-p . (-> (&rest Any) Any))
  (font-otf-alternates . (-> (&rest Any) Any))
  (fontp . (-> (&rest Any) Any))
  (font-put . (-> (&rest Any) Any))
  (fontset-font . (-> (&rest Any) Any))
  (fontset-info . (-> (&rest Any) Any))
  (fontset-list . (-> (&rest Any) Any))
  (fontset-list-all . (-> (&rest Any) Any))
  (font-shape-gstring . (-> (&rest Any) Any))
  (font-spec . (-> (&rest Any) Any))
  (font-variation-glyphs . (-> (&rest Any) Any))
  (font-xlfd-name . (-> (&rest Any) Any))
  (force-mode-line-update . (-> (&rest Any) Any))
  (force-window-update . (-> (&rest Any) Any))
  (format . (-> (&rest Any) Any))
  (format-message . (-> (&rest Any) Any))
  (format-mode-line . (-> (&rest Any) Any))
  (format-network-address . (-> (&rest Any) Any))
  (format-time-string . (-> (&rest Any) Any))
  (forward-char . (-> (&rest Any) Any))
  (forward-comment . (-> (&rest Any) Any))
  (forward-line . (-> (&rest Any) Any))
  (forward-word . (-> (&rest Any) Any))
  (frame-after-make-frame . (-> (&rest Any) Any))
  (frame-ancestor-p . (-> (&rest Any) Any))
  (frame-bottom-divider-width . (-> (&rest Any) Any))
  (frame-char-height . (-> (&rest Any) Any))
  (frame-char-width . (-> (&rest Any) Any))
  (frame-child-frame-border-width . (-> (&rest Any) Any))
  (frame--face-hash-table . (-> (&rest Any) Any))
  (frame-first-window . (-> (&rest Any) Any))
  (frame-focus . (-> (&rest Any) Any))
  (frame-font-cache . (-> (&rest Any) Any))
  (frame-fringe-width . (-> (&rest Any) Any))
  (frame-internal-border-width . (-> (&rest Any) Any))
  (frame-list . (-> (&rest Any) Any))
  (frame-live-p . (-> (&rest Any) Any))
  (frame-native-height . (-> (&rest Any) Any))
  (frame-native-width . (-> (&rest Any) Any))
  (frame-old-selected-window . (-> (&rest Any) Any))
  (frame-or-buffer-changed-p . (-> (&rest Any) Any))
  (framep . (-> (&rest Any) Any))
  (frame-parameter . (-> (&rest Any) Any))
  (frame-parameters . (-> (&rest Any) Any))
  (frame-parent . (-> (&rest Any) Any))
  (frame-pointer-visible-p . (-> (&rest Any) Any))
  (frame-position . (-> (&rest Any) Any))
  (frame-right-divider-width . (-> (&rest Any) Any))
  (frame-root-window . (-> (&rest Any) Any))
  (frame-scale-factor . (-> (&rest Any) Any))
  (frame-scroll-bar-height . (-> (&rest Any) Any))
  (frame-scroll-bar-width . (-> (&rest Any) Any))
  (frame-selected-window . (-> (&rest Any) Any))
  (frame--set-was-invisible . (-> (&rest Any) Any))
  (frame-terminal . (-> (&rest Any) Any))
  (frame-text-cols . (-> (&rest Any) Any))
  (frame-text-height . (-> (&rest Any) Any))
  (frame-text-lines . (-> (&rest Any) Any))
  (frame-text-width . (-> (&rest Any) Any))
  (frame-total-cols . (-> (&rest Any) Any))
  (frame-total-lines . (-> (&rest Any) Any))
  (frame-visible-p . (-> (&rest Any) Any))
  (frame-windows-min-size . (-> (&rest Any) Any))
  (frame-window-state-change . (-> (&rest Any) Any))
  (frexp . (-> (&rest Any) Any))
  (fringe-bitmaps-at-pos . (-> (&rest Any) Any))
  (fround . (-> (&rest Any) Any))
  (fset . (-> (&rest Any) Any))
  (ftruncate . (-> (&rest Any) Any))
  (funcall . (-> (&rest Any) Any))
  (funcall-interactively . (-> (&rest Any) Any))
  (funcall-with-delayed-message . (-> (&rest Any) Any))
  (func-arity . (-> (&rest Any) Any))
  (function . (-> (&rest Any) Any))
  (function-equal . (-> (&rest Any) Any))
  (functionp . (-> (&rest Any) Any))
  (gap-position . (-> (&rest Any) Any))
  (gap-size . (-> (&rest Any) Any))
  (garbage-collect . (-> (&rest Any) Any))
  (garbage-collect-maybe . (-> (&rest Any) Any))
  (generate-new-buffer-name . (-> (&rest Any) Any))
  (get . (-> (&rest Any) Any))
  (get-buffer . (-> (&rest Any) Any))
  (get-buffer-create . (-> (&rest Any) Any))
  (get-buffer-process . (-> (&rest Any) Any))
  (get-buffer-window . (-> (&rest Any) Any))
  (get-buffer-xwidgets . (-> (&rest Any) Any))
  (get-byte . (-> (&rest Any) Any))
  (get-char-property . (-> (&rest Any) Any))
  (get-char-property-and-overlay . (-> (&rest Any) Any))
  (get-display-property . (-> (&rest Any) Any))
  (getenv-internal . (-> (&rest Any) Any))
  (get-file-buffer . (-> (&rest Any) Any))
  (get-file-char . (-> (&rest Any) Any))
  (gethash . (-> (&rest Any) Any))
  (get-internal-run-time . (-> (&rest Any) Any))
  (get-load-suffixes . (-> (&rest Any) Any))
  (get-pos-property . (-> (&rest Any) Any))
  (get-process . (-> (&rest Any) Any))
  (get-screen-color . (-> (&rest Any) Any))
  (get-text-property . (-> (&rest Any) Any))
  (get-truename-buffer . (-> (&rest Any) Any))
  (get-unicode-property-internal . (-> (&rest Any) Any))
  (get-unused-category . (-> (&rest Any) Any))
  (get-unused-iso-final-char . (-> (&rest Any) Any))
  (get-variable-watchers . (-> (&rest Any) Any))
  (gfile-add-watch . (-> (&rest Any) Any))
  (gfile-monitor-name . (-> (&rest Any) Any))
  (gfile-rm-watch . (-> (&rest Any) Any))
  (gfile-valid-p . (-> (&rest Any) Any))
  (gnutls-asynchronous-parameters . (-> (&rest Any) Any))
  (gnutls-available-p . (-> (&rest Any) Any))
  (gnutls-boot . (-> (&rest Any) Any))
  (gnutls-bye . (-> (&rest Any) Any))
  (gnutls-ciphers . (-> (&rest Any) Any))
  (gnutls-deinit . (-> (&rest Any) Any))
  (gnutls-digests . (-> (&rest Any) Any))
  (gnutls-error-fatalp . (-> (&rest Any) Any))
  (gnutls-errorp . (-> (&rest Any) Any))
  (gnutls-error-string . (-> (&rest Any) Any))
  (gnutls-format-certificate . (-> (&rest Any) Any))
  (gnutls-get-initstage . (-> (&rest Any) Any))
  (gnutls-hash-digest . (-> (&rest Any) Any))
  (gnutls-hash-mac . (-> (&rest Any) Any))
  (gnutls-macs . (-> (&rest Any) Any))
  (gnutls-peer-status . (-> (&rest Any) Any))
  (gnutls-peer-status-warning-describe . (-> (&rest Any) Any))
  (gnutls-symmetric-decrypt . (-> (&rest Any) Any))
  (gnutls-symmetric-encrypt . (-> (&rest Any) Any))
  (goto-char . (-> (&rest Any) Any))
  (gpm-mouse-start . (-> (&rest Any) Any))
  (gpm-mouse-stop . (-> (&rest Any) Any))
  (group-gid . (-> (&rest Any) Any))
  (group-name . (-> (&rest Any) Any))
  (group-real-gid . (-> (&rest Any) Any))
  (haiku-display-monitor-attributes-list . (-> (&rest Any) Any))
  (haiku-drag-message . (-> (&rest Any) Any))
  (haiku-frame-edges . (-> (&rest Any) Any))
  (haiku-frame-geometry . (-> (&rest Any) Any))
  (haiku-frame-list-z-order . (-> (&rest Any) Any))
  (haiku-frame-restack . (-> (&rest Any) Any))
  (haiku-get-version-string . (-> (&rest Any) Any))
  (haiku-menu-bar-open . (-> (&rest Any) Any))
  (haiku-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (haiku-notifications-notify . (-> (&rest Any) Any))
  (haiku-put-resource . (-> (&rest Any) Any))
  (haiku-read-file-name . (-> (&rest Any) Any))
  (haiku-roster-launch . (-> (&rest Any) Any))
  (haiku-save-session-reply . (-> (&rest Any) Any))
  (haiku-selection-data . (-> (&rest Any) Any))
  (haiku-selection-owner-p . (-> (&rest Any) Any))
  (haiku-selection-put . (-> (&rest Any) Any))
  (haiku-selection-timestamp . (-> (&rest Any) Any))
  (haiku-send-message . (-> (&rest Any) Any))
  (haiku-set-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (haiku-write-node-attribute . (-> (&rest Any) Any))
  (handle-save-session . (-> (&rest Any) Any))
  (handle-switch-frame . (-> (&rest Any) Any))
  (hash-table-count . (-> (&rest Any) Any))
  (hash-table-p . (-> (&rest Any) Any))
  (hash-table-rehash-size . (-> (&rest Any) Any))
  (hash-table-rehash-threshold . (-> (&rest Any) Any))
  (hash-table-size . (-> (&rest Any) Any))
  (hash-table-test . (-> (&rest Any) Any))
  (hash-table-weakness . (-> (&rest Any) Any))
  (help--describe-vector . (-> (&rest Any) Any))
  (iconify-frame . (-> (&rest Any) Any))
  (identity . (-> (&rest Any) Any))
  (if . (-> (&rest Any) Any))
  (image-cache-size . (-> (&rest Any) Any))
  (image-flush . (-> (&rest Any) Any))
  (imagemagick-types . (-> (&rest Any) Any))
  (image-mask-p . (-> (&rest Any) Any))
  (image-metadata . (-> (&rest Any) Any))
  (imagep . (-> (&rest Any) Any))
  (image-size . (-> (&rest Any) Any))
  (image-transforms-p . (-> (&rest Any) Any))
  (indent-to . (-> (&rest Any) Any))
  (indirect-function . (-> (&rest Any) Any))
  (indirect-variable . (-> (&rest Any) Any))
  (init-image-library . (-> (&rest Any) Any))
  (innermost-minibuffer-p . (-> (&rest Any) Any))
  (inotify-add-watch . (-> (&rest Any) Any))
  (inotify-allocated-p . (-> (&rest Any) Any))
  (inotify-rm-watch . (-> (&rest Any) Any))
  (inotify-valid-p . (-> (&rest Any) Any))
  (inotify-watch-list . (-> (&rest Any) Any))
  (input-pending-p . (-> (&rest Any) Any))
  (insert . (-> (&rest Any) Any))
  (insert-and-inherit . (-> (&rest Any) Any))
  (insert-before-markers . (-> (&rest Any) Any))
  (insert-before-markers-and-inherit . (-> (&rest Any) Any))
  (insert-buffer-substring . (-> (&rest Any) Any))
  (insert-byte . (-> (&rest Any) Any))
  (insert-char . (-> (&rest Any) Any))
  (insert-file-contents . (-> (&rest Any) Any))
  (insert-startup-screen . (-> (&rest Any) Any))
  (int86 . (-> (&rest Any) Any))
  (integer-or-marker-p . (-> (&rest Any) Any))
  (integerp . (-> (&rest Any) Any))
  (interactive . (-> (&rest Any) Any))
  (interactive-form . (-> (&rest Any) Any))
  (intern . (-> (&rest Any) Any))
  (internal-char-font . (-> (&rest Any) Any))
  (internal-complete-buffer . (-> (&rest Any) Any))
  (internal-copy-lisp-face . (-> (&rest Any) Any))
  (internal-decode-string-utf-8 . (-> (&rest Any) Any))
  (internal-default-interrupt-process . (-> (&rest Any) Any))
  (internal-default-process-filter . (-> (&rest Any) Any))
  (internal-default-process-sentinel . (-> (&rest Any) Any))
  (internal-default-signal-process . (-> (&rest Any) Any))
  (internal--define-uninitialized-variable . (-> (&rest Any) Any))
  (internal-describe-syntax-value . (-> (&rest Any) Any))
  (internal-encode-string-utf-8 . (-> (&rest Any) Any))
  (internal-event-symbol-parse-modifiers . (-> (&rest Any) Any))
  (internal-face-x-get-resource . (-> (&rest Any) Any))
  (internal-get-lisp-face-attribute . (-> (&rest Any) Any))
  (internal-handle-focus-in . (-> (&rest Any) Any))
  (internal--labeled-narrow-to-region . (-> (&rest Any) Any))
  (internal--labeled-widen . (-> (&rest Any) Any))
  (internal-lisp-face-attribute-values . (-> (&rest Any) Any))
  (internal-lisp-face-empty-p . (-> (&rest Any) Any))
  (internal-lisp-face-equal-p . (-> (&rest Any) Any))
  (internal-lisp-face-p . (-> (&rest Any) Any))
  (internal-make-lisp-face . (-> (&rest Any) Any))
  (internal-make-var-non-special . (-> (&rest Any) Any))
  (internal-merge-in-global-face . (-> (&rest Any) Any))
  (internal-set-alternative-font-family-alist . (-> (&rest Any) Any))
  (internal-set-alternative-font-registry-alist . (-> (&rest Any) Any))
  (internal--set-buffer-modified-tick . (-> (&rest Any) Any))
  (internal-set-font-selection-order . (-> (&rest Any) Any))
  (internal-set-lisp-face-attribute . (-> (&rest Any) Any))
  (internal-set-lisp-face-attribute-from-resource . (-> (&rest Any) Any))
  (internal-show-cursor . (-> (&rest Any) Any))
  (internal-show-cursor-p . (-> (&rest Any) Any))
  (internal-stack-stats . (-> (&rest Any) Any))
  (internal-subr-documentation . (-> (&rest Any) Any))
  (internal--track-mouse . (-> (&rest Any) Any))
  (intern-soft . (-> (&rest Any) Any))
  (interrupt-process . (-> (&rest Any) Any))
  (invisible-p . (-> (&rest Any) Any))
  (invocation-directory . (-> (&rest Any) Any))
  (invocation-name . (-> (&rest Any) Any))
  (isnan . (-> (&rest Any) Any))
  (iso-charset . (-> (&rest Any) Any))
  (json--available-p . (-> (&rest Any) Any))
  (json-insert . (-> (&rest Any) Any))
  (json-parse-buffer . (-> (&rest Any) Any))
  (json-parse-string . (-> (&rest Any) Any))
  (json-serialize . (-> (&rest Any) Any))
  (key-binding . (-> (&rest Any) Any))
  (keyboard-coding-system . (-> (&rest Any) Any))
  (key-description . (-> (&rest Any) Any))
  (keymap--get-keyelt . (-> (&rest Any) Any))
  (keymapp . (-> (&rest Any) Any))
  (keymap-parent . (-> (&rest Any) Any))
  (keymap-prompt . (-> (&rest Any) Any))
  (keywordp . (-> (&rest Any) Any))
  (kill-all-local-variables . (-> (&rest Any) Any))
  (kill-buffer . (-> (&rest Any) Any))
  (kill-emacs . (-> (&rest Any) Any))
  (kill-local-variable . (-> (&rest Any) Any))
  (kill-process . (-> (&rest Any) Any))
  (kill-xwidget . (-> (&rest Any) Any))
  (kqueue-add-watch . (-> (&rest Any) Any))
  (kqueue-rm-watch . (-> (&rest Any) Any))
  (kqueue-valid-p . (-> (&rest Any) Any))
  (last-nonminibuffer-frame . (-> (&rest Any) Any))
  (lcms2-available-p . (-> (&rest Any) Any))
  (lcms-cam02-ucs . (-> (&rest Any) Any))
  (lcms-cie-de2000 . (-> (&rest Any) Any))
  (lcms-jab->jch . (-> (&rest Any) Any))
  (lcms-jch->jab . (-> (&rest Any) Any))
  (lcms-jch->xyz . (-> (&rest Any) Any))
  (lcms-temp->white-point . (-> (&rest Any) Any))
  (lcms-xyz->jch . (-> (&rest Any) Any))
  (ldexp . (-> (&rest Any) Any))
  (length . (-> (sequence) integer))
  (length< . (-> (&rest Any) Any))
  (length= . (-> (&rest Any) Any))
  (length> . (-> (&rest Any) Any))
  (let . (-> (&rest Any) Any))
  (let* . (-> (&rest Any) Any))
  (libxml-available-p . (-> (&rest Any) Any))
  (libxml-parse-html-region . (-> (&rest Any) Any))
  (libxml-parse-xml-region . (-> (&rest Any) Any))
  (line-beginning-position . (-> (&rest Any) Any))
  (line-end-position . (-> (&rest Any) Any))
  (line-number-at-pos . (-> (&rest Any) Any))
  (line-number-display-width . (-> (&rest Any) Any))
  (line-pixel-height . (-> (&rest Any) Any))
  (list . (-> (&rest Any) list))
  (list-fonts . (-> (&rest Any) Any))
  (listp . (-> (&rest Any) Any))
  (list-system-processes . (-> (&rest Any) Any))
  (load . (-> (&rest Any) Any))
  (load-average . (-> (&rest Any) Any))
  (locale-info . (-> (&rest Any) Any))
  (local-variable-if-set-p . (-> (&rest Any) Any))
  (local-variable-p . (-> (&rest Any) Any))
  (locate-file-internal . (-> (&rest Any) Any))
  (lock-buffer . (-> (&rest Any) Any))
  (lock-file . (-> (&rest Any) Any))
  (log . (-> (&rest Any) Any))
  (logand . (-> (&rest Any) Any))
  (logb . (-> (&rest Any) Any))
  (logcount . (-> (&rest Any) Any))
  (logior . (-> (&rest Any) Any))
  (lognot . (-> (&rest Any) Any))
  (logxor . (-> (&rest Any) Any))
  (long-line-optimizations-p . (-> (&rest Any) Any))
  (looking-at . (-> (&rest Any) Any))
  (lookup-image . (-> (&rest Any) Any))
  (lookup-image-map . (-> (&rest Any) Any))
  (lookup-key . (-> (&rest Any) Any))
  (lossage-size . (-> (&rest Any) Any))
  (lower-frame . (-> (&rest Any) Any))
  (lread--substitute-object-in-subtree . (-> (&rest Any) Any))
  (macroexpand . (-> (&rest Any) Any))
  (make-bool-vector . (-> (&rest Any) Any))
  (make-byte-code . (-> (&rest Any) Any))
  (make-category-set . (-> (&rest Any) Any))
  (make-category-table . (-> (&rest Any) Any))
  (make-char . (-> (&rest Any) Any))
  (make-char-table . (-> (&rest Any) Any))
  (make-closure . (-> (&rest Any) Any))
  (make-condition-variable . (-> (&rest Any) Any))
  (make-directory-internal . (-> (&rest Any) Any))
  (make-finalizer . (-> (&rest Any) Any))
  (make-frame-invisible . (-> (&rest Any) Any))
  (make-frame-visible . (-> (&rest Any) Any))
  (make-hash-table . (-> (&rest Any) Any))
  (make-indirect-buffer . (-> (&rest Any) Any))
  (make-keymap . (-> (&rest Any) Any))
  (make-list . (-> (&rest Any) Any))
  (make-local-variable . (-> (&rest Any) Any))
  (make-marker . (-> (&rest Any) Any))
  (make-mutex . (-> (&rest Any) Any))
  (make-network-process . (-> (&rest Any) Any))
  (make-overlay . (-> (&rest Any) Any))
  (make-pipe-process . (-> (&rest Any) Any))
  (make-process . (-> (&rest Any) Any))
  (make-record . (-> (&rest Any) Any))
  (make-serial-process . (-> (&rest Any) Any))
  (make-sparse-keymap . (-> (&rest Any) Any))
  (make-string . (-> (&rest Any) Any))
  (make-symbol . (-> (&rest Any) Any))
  (make-symbolic-link . (-> (&rest Any) Any))
  (make-temp-file-internal . (-> (&rest Any) Any))
  (make-temp-name . (-> (&rest Any) Any))
  (make-terminal-frame . (-> (&rest Any) Any))
  (make-thread . (-> (&rest Any) Any))
  (make-variable-buffer-local . (-> (&rest Any) Any))
  (make-vector . (-> (&rest Any) Any))
  (make-xwidget . (-> (&rest Any) Any))
  (makunbound . (-> (&rest Any) Any))
  (malloc-info . (-> (&rest Any) Any))
  (malloc-trim . (-> (&rest Any) Any))
  (mapatoms . (-> (&rest Any) Any))
  (mapbacktrace . (-> (&rest Any) Any))
  (mapc . (-> ((-> ('a) 'b) (Sequence 'a)) (Sequence 'a)))
  (mapcan . (-> (&rest Any) Any))
  (mapcar . (-> (&rest Any) Any))
  (mapcar . (-> ((-> ('a) 'b) (Sequence 'a)) (Sequence 'b)))
  (map-charset-chars . (-> (&rest Any) Any))
  (map-char-table . (-> (&rest Any) Any))
  (mapconcat . (-> (&rest Any) Any))
  (maphash . (-> (&rest Any) Any))
  (map-keymap . (-> (&rest Any) Any))
  (map-keymap-internal . (-> (&rest Any) Any))
  (marker-buffer . (-> (&rest Any) Any))
  (marker-insertion-type . (-> (&rest Any) Any))
  (markerp . (-> (&rest Any) Any))
  (marker-position . (-> (&rest Any) Any))
  (mark-marker . (-> (&rest Any) Any))
  (match-beginning . (-> (&rest Any) Any))
  (match-data . (-> (&rest Any) Any))
  (match-data--translate . (-> (&rest Any) Any))
  (match-end . (-> (&rest Any) Any))
  (matching-paren . (-> (&rest Any) Any))
  (max . (-> (&rest Any) Any))
  (max-char . (-> (&rest Any) Any))
  (md5 . (-> (&rest Any) Any))
  (member . (-> (&rest Any) Any))
  (memory-info . (-> (&rest Any) Any))
  (memory-use-counts . (-> (&rest Any) Any))
  (memq . (-> (&rest Any) Any))
  (memql . (-> (&rest Any) Any))
  (menu-bar-menu-at-x-y . (-> (&rest Any) Any))
  (menu-or-popup-active-p . (-> (&rest Any) Any))
  (merge-face-attribute . (-> (&rest Any) Any))
  (message . (-> (&rest Any) Any))
  (message-box . (-> (&rest Any) Any))
  (message-or-box . (-> (&rest Any) Any))
  (min . (-> (&rest Any) Any))
  (minibuffer-contents . (-> (&rest Any) Any))
  (minibuffer-contents-no-properties . (-> (&rest Any) Any))
  (minibuffer-depth . (-> (&rest Any) Any))
  (minibuffer-innermost-command-loop-p . (-> (&rest Any) Any))
  (minibufferp . (-> (&rest Any) Any))
  (minibuffer-prompt . (-> (&rest Any) Any))
  (minibuffer-prompt-end . (-> (&rest Any) Any))
  (minibuffer-selected-window . (-> (&rest Any) Any))
  (minibuffer-window . (-> (&rest Any) Any))
  (minor-mode-key-binding . (-> (&rest Any) Any))
  (mod . (-> (&rest Any) Any))
  (modify-category-entry . (-> (&rest Any) Any))
  (modify-frame-parameters . (-> (&rest Any) Any))
  (modify-syntax-entry . (-> (&rest Any) Any))
  (module-function-p . (-> (&rest Any) Any))
  (module-load . (-> (&rest Any) Any))
  (mouse-pixel-position . (-> (&rest Any) Any))
  (mouse-position . (-> (&rest Any) Any))
  (move-overlay . (-> (&rest Any) Any))
  (move-point-visually . (-> (&rest Any) Any))
  (move-to-column . (-> (&rest Any) Any))
  (move-to-window-line . (-> (&rest Any) Any))
  (msdos-downcase-filename . (-> (&rest Any) Any))
  (msdos-long-file-names . (-> (&rest Any) Any))
  (msdos-memget . (-> (&rest Any) Any))
  (msdos-memput . (-> (&rest Any) Any))
  (msdos-mouse-disable . (-> (&rest Any) Any))
  (msdos-mouse-enable . (-> (&rest Any) Any))
  (msdos-mouse-init . (-> (&rest Any) Any))
  (msdos-mouse-p . (-> (&rest Any) Any))
  (msdos-remember-default-colors . (-> (&rest Any) Any))
  (msdos-set-keyboard . (-> (&rest Any) Any))
  (msdos-set-mouse-buttons . (-> (&rest Any) Any))
  (multibyte-char-to-unibyte . (-> (&rest Any) Any))
  (multibyte-string-p . (-> (&rest Any) Any))
  (mutex-lock . (-> (&rest Any) Any))
  (mutex-name . (-> (&rest Any) Any))
  (mutexp . (-> (&rest Any) Any))
  (mutex-unlock . (-> (&rest Any) Any))
  (narrow-to-region . (-> (&rest Any) Any))
  (native-comp-available-p . (-> (&rest Any) Any))
  (native-comp-unit-file . (-> (&rest Any) Any))
  (native-comp-unit-set-file . (-> (&rest Any) Any))
  (native-elisp-load . (-> (&rest Any) Any))
  (natnump . (-> (&rest Any) Any))
  (nconc . (-> (&rest Any) Any))
  (network-interface-info . (-> (&rest Any) Any))
  (network-interface-list . (-> (&rest Any) Any))
  (network-lookup-address-info . (-> (&rest Any) Any))
  (new-fontset . (-> (&rest Any) Any))
  (newline-cache-check . (-> (&rest Any) Any))
  (next-char-property-change . (-> (&rest Any) Any))
  (next-frame . (-> (&rest Any) Any))
  (next-overlay-change . (-> (&rest Any) Any))
  (next-property-change . (-> (&rest Any) Any))
  (next-read-file-uses-dialog-p . (-> (&rest Any) Any))
  (next-single-char-property-change . (-> (&rest Any) Any))
  (next-single-property-change . (-> (&rest Any) Any))
  (next-window . (-> (&rest Any) Any))
  (ngettext . (-> (&rest Any) Any))
  (nlistp . (-> (&rest Any) Any))
  (nreverse . (-> (&rest Any) Any))
  (ntake . (-> (&rest Any) Any))
  (nth . (-> (&rest Any) Any))
  (nthcdr . (-> (&rest Any) Any))
  (null . (-> (&rest Any) Any))
  (number-or-marker-p . (-> (&rest Any) Any))
  (numberp . (-> (&rest Any) Any))
  (number-to-string . (-> (number) string))
  (num-processors . (-> (&rest Any) Any))
  (object-intervals . (-> (&rest Any) Any))
  (old-selected-frame . (-> (&rest Any) Any))
  (old-selected-window . (-> (&rest Any) Any))
  (open-dribble-file . (-> (&rest Any) Any))
  (open-font . (-> (&rest Any) Any))
  (open-termscript . (-> (&rest Any) Any))
  (optimize-char-table . (-> (&rest Any) Any))
  (or . (-> (&rest Any) Any))
  (other-buffer . (-> (&rest Any) Any))
  (other-window-for-scrolling . (-> (&rest Any) Any))
  (overlay-buffer . (-> (&rest Any) Any))
  (overlay-end . (-> (&rest Any) Any))
  (overlay-get . (-> (&rest Any) Any))
  (overlay-lists . (-> (&rest Any) Any))
  (overlayp . (-> (&rest Any) Any))
  (overlay-properties . (-> (&rest Any) Any))
  (overlay-put . (-> (&rest Any) Any))
  (overlay-recenter . (-> (&rest Any) Any))
  (overlays-at . (-> (&rest Any) Any))
  (overlays-in . (-> (&rest Any) Any))
  (overlay-start . (-> (&rest Any) Any))
  (overlay-tree . (-> (&rest Any) Any))
  (parse-partial-sexp . (-> (&rest Any) Any))
  (pdumper-stats . (-> (&rest Any) Any))
  (pgtk-backend-display-class . (-> (&rest Any) Any))
  (pgtk-disown-selection-internal . (-> (&rest Any) Any))
  (pgtk-display-monitor-attributes-list . (-> (&rest Any) Any))
  (pgtk-drop-finish . (-> (&rest Any) Any))
  (pgtk-font-name . (-> (&rest Any) Any))
  (pgtk-frame-edges . (-> (&rest Any) Any))
  (pgtk-frame-geometry . (-> (&rest Any) Any))
  (pgtk-frame-restack . (-> (&rest Any) Any))
  (pgtk-get-page-setup . (-> (&rest Any) Any))
  (pgtk-get-selection-internal . (-> (&rest Any) Any))
  (pgtk-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (pgtk-own-selection-internal . (-> (&rest Any) Any))
  (pgtk-page-setup-dialog . (-> (&rest Any) Any))
  (pgtk-print-frames-dialog . (-> (&rest Any) Any))
  (pgtk-register-dnd-targets . (-> (&rest Any) Any))
  (pgtk-selection-exists-p . (-> (&rest Any) Any))
  (pgtk-selection-owner-p . (-> (&rest Any) Any))
  (pgtk-set-monitor-scale-factor . (-> (&rest Any) Any))
  (pgtk-set-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (pgtk-set-resource . (-> (&rest Any) Any))
  (pgtk-update-drop-status . (-> (&rest Any) Any))
  (pgtk-use-im-context . (-> (&rest Any) Any))
  (play-sound-internal . (-> (&rest Any) Any))
  (plist-get . (-> (&rest Any) Any))
  (plist-member . (-> (&rest Any) Any))
  (plist-put . (-> (&rest Any) Any))
  (point . (-> (&rest Any) Any))
  (point-marker . (-> (&rest Any) Any))
  (point-max . (-> (&rest Any) Any))
  (point-max-marker . (-> (&rest Any) Any))
  (point-min . (-> (&rest Any) Any))
  (point-min-marker . (-> (&rest Any) Any))
  (pos-bol . (-> (&rest Any) Any))
  (pos-eol . (-> (&rest Any) Any))
  (position-bytes . (-> (&rest Any) Any))
  (position-symbol . (-> (&rest Any) Any))
  (posix-looking-at . (-> (&rest Any) Any))
  (posix-search-backward . (-> (&rest Any) Any))
  (posix-search-forward . (-> (&rest Any) Any))
  (posix-string-match . (-> (&rest Any) Any))
  (posn-at-point . (-> (&rest Any) Any))
  (posn-at-x-y . (-> (&rest Any) Any))
  (pos-visible-in-window-p . (-> (&rest Any) Any))
  (preceding-char . (-> (&rest Any) Any))
  (prefix-numeric-value . (-> (&rest Any) Any))
  (previous-char-property-change . (-> (&rest Any) Any))
  (previous-frame . (-> (&rest Any) Any))
  (previous-overlay-change . (-> (&rest Any) Any))
  (previous-property-change . (-> (&rest Any) Any))
  (previous-single-char-property-change . (-> (&rest Any) Any))
  (previous-single-property-change . (-> (&rest Any) Any))
  (previous-window . (-> (&rest Any) Any))
  (prin1 . (-> (&rest Any) Any))
  (prin1-to-string . (-> (&rest Any) Any))
  (princ . (-> (&rest Any) Any))
  (print . (-> (&rest Any) Any))
  (print--preprocess . (-> (&rest Any) Any))
  (process-attributes . (-> (&rest Any) Any))
  (process-buffer . (-> (&rest Any) Any))
  (process-coding-system . (-> (&rest Any) Any))
  (process-command . (-> (&rest Any) Any))
  (process-connection . (-> (&rest Any) Any))
  (process-contact . (-> (&rest Any) Any))
  (process-datagram-address . (-> (&rest Any) Any))
  (process-exit-status . (-> (&rest Any) Any))
  (process-filter . (-> (&rest Any) Any))
  (process-id . (-> (&rest Any) Any))
  (process-inherit-coding-system-flag . (-> (&rest Any) Any))
  (process-list . (-> (&rest Any) Any))
  (process-mark . (-> (&rest Any) Any))
  (process-name . (-> (&rest Any) Any))
  (processp . (-> (&rest Any) Any))
  (process-plist . (-> (&rest Any) Any))
  (process-query-on-exit-flag . (-> (&rest Any) Any))
  (process-running-child-p . (-> (&rest Any) Any))
  (process-send-eof . (-> (&rest Any) Any))
  (process-send-region . (-> (&rest Any) Any))
  (process-send-string . (-> (&rest Any) Any))
  (process-sentinel . (-> (&rest Any) Any))
  (process-status . (-> (&rest Any) Any))
  (process-thread . (-> (&rest Any) Any))
  (process-tty-name . (-> (&rest Any) Any))
  (process-type . (-> (&rest Any) Any))
  (profiler-cpu-log . (-> (&rest Any) Any))
  (profiler-cpu-running-p . (-> (&rest Any) Any))
  (profiler-cpu-start . (-> (&rest Any) Any))
  (profiler-cpu-stop . (-> (&rest Any) Any))
  (profiler-memory-log . (-> (&rest Any) Any))
  (profiler-memory-running-p . (-> (&rest Any) Any))
  (profiler-memory-start . (-> (&rest Any) Any))
  (profiler-memory-stop . (-> (&rest Any) Any))
  (prog1 . (-> (&rest Any) Any))
  (progn . (-> (&rest Any) Any))
  (proper-list-p . (-> (&rest Any) Any))
  (propertize . (-> (&rest Any) Any))
  (provide . (-> (&rest Any) Any))
  (purecopy . (-> (&rest Any) Any))
  (put . (-> (&rest Any) Any))
  (puthash . (-> (&rest Any) Any))
  (put-text-property . (-> (&rest Any) Any))
  (put-unicode-property-internal . (-> (&rest Any) Any))
  (query-font . (-> (&rest Any) Any))
  (query-fontset . (-> (&rest Any) Any))
  (quit-process . (-> (&rest Any) Any))
  (quote . (-> (&rest Any) Any))
  (raise-frame . (-> (&rest Any) Any))
  (random . (-> (&rest Any) Any))
  (rassoc . (-> (&rest Any) Any))
  (rassq . (-> (&rest Any) Any))
  (read . (-> (&rest Any) Any))
  (read-buffer . (-> (&rest Any) Any))
  (read-char . (-> (&rest Any) Any))
  (read-char-exclusive . (-> (&rest Any) Any))
  (read-coding-system . (-> (&rest Any) Any))
  (read-command . (-> (&rest Any) Any))
  (read-event . (-> (&rest Any) Any))
  (read-from-minibuffer . (-> (&rest Any) Any))
  (read-from-string . (-> (&rest Any) Any))
  (read-function . (-> (&rest Any) Any))
  (read-key-sequence . (-> (&rest Any) Any))
  (read-key-sequence-vector . (-> (&rest Any) Any))
  (read-non-nil-coding-system . (-> (&rest Any) Any))
  (read-positioning-symbols . (-> (&rest Any) Any))
  (read-string . (-> (&rest Any) Any))
  (read-variable . (-> (&rest Any) Any))
  (recent-auto-save-p . (-> (&rest Any) Any))
  (recent-doskeys . (-> (&rest Any) Any))
  (recenter . (-> (&rest Any) Any))
  (recent-keys . (-> (&rest Any) Any))
  (reconsider-frame-fonts . (-> (&rest Any) Any))
  (record . (-> (&rest Any) Any))
  (recordp . (-> (&rest Any) Any))
  (recursion-depth . (-> (&rest Any) Any))
  (recursive-edit . (-> (&rest Any) Any))
  (re--describe-compiled . (-> (&rest Any) Any))
  (redirect-debugging-output . (-> (&rest Any) Any))
  (redirect-frame-focus . (-> (&rest Any) Any))
  (redisplay . (-> (&rest Any) Any))
  (redraw-display . (-> (&rest Any) Any))
  (redraw-frame . (-> (&rest Any) Any))
  (regexp-quote . (-> (&rest Any) Any))
  (region-beginning . (-> (&rest Any) Any))
  (region-end . (-> (&rest Any) Any))
  (register-ccl-program . (-> (&rest Any) Any))
  (register-code-conversion-map . (-> (&rest Any) Any))
  (remhash . (-> (&rest Any) Any))
  (remove-list-of-text-properties . (-> (&rest Any) Any))
  (remove-pos-from-symbol . (-> (&rest Any) Any))
  (remove-text-properties . (-> (&rest Any) Any))
  (remove-variable-watcher . (-> (&rest Any) Any))
  (rename-buffer . (-> (&rest Any) Any))
  (rename-file . (-> (&rest Any) Any))
  (replace-buffer-contents . (-> (&rest Any) Any))
  (replace-match . (-> (&rest Any) Any))
  (require . (-> (&rest Any) Any))
  (re-search-backward . (-> (&rest Any) Any))
  (re-search-forward . (-> (&rest Any) Any))
  (resize-mini-window-internal . (-> (&rest Any) Any))
  (restore-buffer-modified-p . (-> (&rest Any) Any))
  (resume-tty . (-> (&rest Any) Any))
  (reverse . (-> (&rest Any) Any))
  (round . (-> (&rest Any) Any))
  (run-hooks . (-> (&rest Any) Any))
  (run-hook-with-args . (-> (&rest Any) Any))
  (run-hook-with-args-until-failure . (-> (&rest Any) Any))
  (run-hook-with-args-until-success . (-> (&rest Any) Any))
  (run-hook-wrapped . (-> (&rest Any) Any))
  (run-window-configuration-change-hook . (-> (&rest Any) Any))
  (run-window-scroll-functions . (-> (&rest Any) Any))
  (safe-length . (-> (&rest Any) Any))
  (save-current-buffer . (-> (&rest Any) Any))
  (save-excursion . (-> (&rest Any) Any))
  (save-restriction . (-> (&rest Any) Any))
  (scan-lists . (-> (&rest Any) Any))
  (scan-sexps . (-> (&rest Any) Any))
  (scroll-down . (-> (&rest Any) Any))
  (scroll-left . (-> (&rest Any) Any))
  (scroll-right . (-> (&rest Any) Any))
  (scroll-up . (-> (&rest Any) Any))
  (search-backward . (-> (&rest Any) Any))
  (search-forward . (-> (&rest Any) Any))
  (secure-hash . (-> (&rest Any) Any))
  (secure-hash-algorithms . (-> (&rest Any) Any))
  (selected-frame . (-> (&rest Any) Any))
  (selected-window . (-> (&rest Any) Any))
  (select-frame . (-> (&rest Any) Any))
  (select-window . (-> (&rest Any) Any))
  (self-insert-command . (-> (&rest Any) Any))
  (send-string-to-terminal . (-> (&rest Any) Any))
  (sequencep . (-> (&rest Any) Any))
  (serial-process-configure . (-> (&rest Any) Any))
  (set . (-> (&rest Any) Any))
  (set-binary-mode . (-> (&rest Any) Any))
  (set-buffer . (-> (&rest Any) Any))
  (set-buffer-auto-saved . (-> (&rest Any) Any))
  (set-buffer-major-mode . (-> (&rest Any) Any))
  (set-buffer-modified-p . (-> (&rest Any) Any))
  (set-buffer-multibyte . (-> (&rest Any) Any))
  (set-buffer-redisplay . (-> (&rest Any) Any))
  (setcar . (-> (&rest Any) Any))
  (set-case-table . (-> (&rest Any) Any))
  (set-category-table . (-> (&rest Any) Any))
  (setcdr . (-> (&rest Any) Any))
  (set-charset-plist . (-> (&rest Any) Any))
  (set-charset-priority . (-> (&rest Any) Any))
  (set-char-table-extra-slot . (-> (&rest Any) Any))
  (set-char-table-parent . (-> (&rest Any) Any))
  (set-char-table-range . (-> (&rest Any) Any))
  (set-coding-system-priority . (-> (&rest Any) Any))
  (set-cursor-size . (-> (&rest Any) Any))
  (set-default . (-> (&rest Any) Any))
  (set-default-file-modes . (-> (&rest Any) Any))
  (set-default-toplevel-value . (-> (&rest Any) Any))
  (set-file-acl . (-> (&rest Any) Any))
  (set-file-modes . (-> (&rest Any) Any))
  (set-file-selinux-context . (-> (&rest Any) Any))
  (set-file-times . (-> (&rest Any) Any))
  (set-fontset-font . (-> (&rest Any) Any))
  (set-frame-height . (-> (&rest Any) Any))
  (set-frame-position . (-> (&rest Any) Any))
  (set-frame-selected-window . (-> (&rest Any) Any))
  (set-frame-size . (-> (&rest Any) Any))
  (set-frame-width . (-> (&rest Any) Any))
  (set-frame-window-state-change . (-> (&rest Any) Any))
  (set-fringe-bitmap-face . (-> (&rest Any) Any))
  (set-input-interrupt-mode . (-> (&rest Any) Any))
  (set-input-meta-mode . (-> (&rest Any) Any))
  (set-input-mode . (-> (&rest Any) Any))
  (set-keyboard-coding-system-internal . (-> (&rest Any) Any))
  (set-keymap-parent . (-> (&rest Any) Any))
  (set-marker . (-> (&rest Any) Any))
  (set-marker-insertion-type . (-> (&rest Any) Any))
  (set-match-data . (-> (&rest Any) Any))
  (set-message-beep . (-> (&rest Any) Any))
  (set-minibuffer-window . (-> (&rest Any) Any))
  (set-mouse-pixel-position . (-> (&rest Any) Any))
  (set-mouse-position . (-> (&rest Any) Any))
  (set-network-process-option . (-> (&rest Any) Any))
  (set-output-flow-control . (-> (&rest Any) Any))
  (setplist . (-> (&rest Any) Any))
  (set-process-buffer . (-> (&rest Any) Any))
  (set-process-coding-system . (-> (&rest Any) Any))
  (set-process-datagram-address . (-> (&rest Any) Any))
  (set-process-filter . (-> (&rest Any) Any))
  (set-process-inherit-coding-system-flag . (-> (&rest Any) Any))
  (set-process-plist . (-> (&rest Any) Any))
  (set-process-query-on-exit-flag . (-> (&rest Any) Any))
  (set-process-sentinel . (-> (&rest Any) Any))
  (set-process-thread . (-> (&rest Any) Any))
  (set-process-window-size . (-> (&rest Any) Any))
  (setq . (-> (&rest Any) Any))
  (set-quit-char . (-> (&rest Any) Any))
  (set-safe-terminal-coding-system-internal . (-> (&rest Any) Any))
  (set-screen-color . (-> (&rest Any) Any))
  (set-standard-case-table . (-> (&rest Any) Any))
  (set-syntax-table . (-> (&rest Any) Any))
  (set-terminal-coding-system-internal . (-> (&rest Any) Any))
  (set-terminal-parameter . (-> (&rest Any) Any))
  (set-text-conversion-style . (-> (&rest Any) Any))
  (set-text-properties . (-> (&rest Any) Any))
  (set--this-command-keys . (-> (&rest Any) Any))
  (set-time-zone-rule . (-> (&rest Any) Any))
  (set-visited-file-modtime . (-> (&rest Any) Any))
  (set-window-buffer . (-> (&rest Any) Any))
  (set-window-combination-limit . (-> (&rest Any) Any))
  (set-window-configuration . (-> (&rest Any) Any))
  (set-window-dedicated-p . (-> (&rest Any) Any))
  (set-window-display-table . (-> (&rest Any) Any))
  (set-window-fringes . (-> (&rest Any) Any))
  (set-window-hscroll . (-> (&rest Any) Any))
  (set-window-margins . (-> (&rest Any) Any))
  (set-window-new-normal . (-> (&rest Any) Any))
  (set-window-new-pixel . (-> (&rest Any) Any))
  (set-window-new-total . (-> (&rest Any) Any))
  (set-window-next-buffers . (-> (&rest Any) Any))
  (set-window-parameter . (-> (&rest Any) Any))
  (set-window-point . (-> (&rest Any) Any))
  (set-window-prev-buffers . (-> (&rest Any) Any))
  (set-window-scroll-bars . (-> (&rest Any) Any))
  (set-window-start . (-> (&rest Any) Any))
  (set-window-vscroll . (-> (&rest Any) Any))
  (set-xwidget-buffer . (-> (&rest Any) Any))
  (set-xwidget-plist . (-> (&rest Any) Any))
  (set-xwidget-query-on-exit-flag . (-> (&rest Any) Any))
  (show-face-resources . (-> (&rest Any) Any))
  (signal . (-> (&rest Any) Any))
  (signal-names . (-> (&rest Any) Any))
  (signal-process . (-> (&rest Any) Any))
  (sin . (-> (&rest Any) Any))
  (single-key-description . (-> (&rest Any) Any))
  (skip-chars-backward . (-> (&rest Any) Any))
  (skip-chars-forward . (-> (&rest Any) Any))
  (skip-syntax-backward . (-> (&rest Any) Any))
  (skip-syntax-forward . (-> (&rest Any) Any))
  (sleep-for . (-> (&rest Any) Any))
  (Snarf-documentation . (-> (&rest Any) Any))
  (sort . (-> (&rest Any) Any))
  (sort-charsets . (-> (&rest Any) Any))
  (special-variable-p . (-> (&rest Any) Any))
  (split-char . (-> (&rest Any) Any))
  (split-window-internal . (-> (&rest Any) Any))
  (sqlite-available-p . (-> (&rest Any) Any))
  (sqlite-close . (-> (&rest Any) Any))
  (sqlite-columns . (-> (&rest Any) Any))
  (sqlite-commit . (-> (&rest Any) Any))
  (sqlite-execute . (-> (&rest Any) Any))
  (sqlite-finalize . (-> (&rest Any) Any))
  (sqlite-load-extension . (-> (&rest Any) Any))
  (sqlite-more-p . (-> (&rest Any) Any))
  (sqlite-next . (-> (&rest Any) Any))
  (sqlite-open . (-> (&rest Any) Any))
  (sqlitep . (-> (&rest Any) Any))
  (sqlite-pragma . (-> (&rest Any) Any))
  (sqlite-rollback . (-> (&rest Any) Any))
  (sqlite-select . (-> (&rest Any) Any))
  (sqlite-transaction . (-> (&rest Any) Any))
  (sqlite-version . (-> (&rest Any) Any))
  (sqrt . (-> (&rest Any) Any))
  (standard-case-table . (-> (&rest Any) Any))
  (standard-category-table . (-> (&rest Any) Any))
  (standard-syntax-table . (-> (&rest Any) Any))
  (start-kbd-macro . (-> (&rest Any) Any))
  (stop-process . (-> (&rest Any) Any))
  (store-kbd-macro-event . (-> (&rest Any) Any))
  (string . (-> (&rest Any) Any))
  (string-as-multibyte . (-> (&rest Any) Any))
  (string-as-unibyte . (-> (&rest Any) Any))
  (string-bytes . (-> (&rest Any) Any))
  (string-collate-equalp . (-> (&rest Any) Any))
  (string-collate-lessp . (-> (&rest Any) Any))
  (string-distance . (-> (&rest Any) Any))
  (string-equal . (-> (&rest Any) Any))
  (string-lessp . (-> (&rest Any) Any))
  (string-make-multibyte . (-> (&rest Any) Any))
  (string-make-unibyte . (-> (&rest Any) Any))
  (string-match . (-> (&rest Any) Any))
  (stringp . (-> (&rest Any) Any))
  (string-search . (-> (&rest Any) Any))
  (string-to-char . (-> (&rest Any) Any))
  (string-to-multibyte . (-> (&rest Any) Any))
  (string-to-number . (-> (&rest Any) Any))
  (string-to-syntax . (-> (&rest Any) Any))
  (string-to-unibyte . (-> (&rest Any) Any))
  (string-version-lessp . (-> (&rest Any) Any))
  (string-width . (-> (&rest Any) Any))
  (subr-arity . (-> (&rest Any) Any))
  (subr-name . (-> (&rest Any) Any))
  (subr-native-comp-unit . (-> (&rest Any) Any))
  (subr-native-elisp-p . (-> (&rest Any) Any))
  (subr-native-lambda-list . (-> (&rest Any) Any))
  (subrp . (-> (&rest Any) Any))
  (subr-type . (-> (&rest Any) Any))
  (subst-char-in-region . (-> (&rest Any) Any))
  (substitute-in-file-name . (-> (&rest Any) Any))
  (substring . (-> (&rest Any) Any))
  (substring-no-properties . (-> (&rest Any) Any))
  (suspend-emacs . (-> (&rest Any) Any))
  (suspend-tty . (-> (&rest Any) Any))
  (suspicious-object . (-> (&rest Any) Any))
  (sxhash-eq . (-> (&rest Any) Any))
  (sxhash-eql . (-> (&rest Any) Any))
  (sxhash-equal . (-> (&rest Any) Any))
  (sxhash-equal-including-properties . (-> (&rest Any) Any))
  (symbol-function . (-> (&rest Any) Any))
  (symbol-name . (-> (&rest Any) Any))
  (symbolp . (-> (&rest Any) Any))
  (symbol-plist . (-> (&rest Any) Any))
  (symbol-value . (-> (&rest Any) Any))
  (symbol-with-pos-p . (-> (&rest Any) Any))
  (symbol-with-pos-pos . (-> (&rest Any) Any))
  (syntax-class-to-char . (-> (&rest Any) Any))
  (syntax-table . (-> (&rest Any) Any))
  (syntax-table-p . (-> (&rest Any) Any))
  (system-groups . (-> (&rest Any) Any))
  (system-move-file-to-trash . (-> (&rest Any) Any))
  (system-name . (-> (&rest Any) Any))
  (system-users . (-> (&rest Any) Any))
  (tab-bar-height . (-> (&rest Any) Any))
  (take . (-> (&rest Any) Any))
  (tan . (-> (&rest Any) Any))
  (terminal-coding-system . (-> (&rest Any) Any))
  (terminal-list . (-> (&rest Any) Any))
  (terminal-live-p . (-> (&rest Any) Any))
  (terminal-name . (-> (&rest Any) Any))
  (terminal-parameter . (-> (&rest Any) Any))
  (terminal-parameters . (-> (&rest Any) Any))
  (terpri . (-> (&rest Any) Any))
  (test-completion . (-> (&rest Any) Any))
  (text-char-description . (-> (&rest Any) Any))
  (text-properties-at . (-> (&rest Any) Any))
  (text-property-any . (-> (&rest Any) Any))
  (text-property-not-all . (-> (&rest Any) Any))
  (text-quoting-style . (-> (&rest Any) Any))
  (this-command-keys . (-> (&rest Any) Any))
  (this-command-keys-vector . (-> (&rest Any) Any))
  (this-single-command-keys . (-> (&rest Any) Any))
  (this-single-command-raw-keys . (-> (&rest Any) Any))
  (thread--blocker . (-> (&rest Any) Any))
  (thread-join . (-> (&rest Any) Any))
  (thread-last-error . (-> (&rest Any) Any))
  (thread-live-p . (-> (&rest Any) Any))
  (thread-name . (-> (&rest Any) Any))
  (threadp . (-> (&rest Any) Any))
  (thread-signal . (-> (&rest Any) Any))
  (thread-yield . (-> (&rest Any) Any))
  (throw . (-> (&rest Any) Any))
  (time-add . (-> (&rest Any) Any))
  (time-convert . (-> (&rest Any) Any))
  (time-equal-p . (-> (&rest Any) Any))
  (time-less-p . (-> (&rest Any) Any))
  (time-subtract . (-> (&rest Any) Any))
  (tool-bar-get-system-style . (-> (&rest Any) Any))
  (tool-bar-height . (-> (&rest Any) Any))
  (tool-bar-pixel-width . (-> (&rest Any) Any))
  (top-level . (-> (&rest Any) Any))
  (trace-redisplay . (-> (&rest Any) Any))
  (trace-to-stderr . (-> (&rest Any) Any))
  (translate-region-internal . (-> (&rest Any) Any))
  (transpose-regions . (-> (&rest Any) Any))
  (treesit-available-p . (-> (&rest Any) Any))
  (treesit-compiled-query-p . (-> (&rest Any) Any))
  (treesit-induce-sparse-tree . (-> (&rest Any) Any))
  (treesit-language-abi-version . (-> (&rest Any) Any))
  (treesit-language-available-p . (-> (&rest Any) Any))
  (treesit-library-abi-version . (-> (&rest Any) Any))
  (treesit-node-check . (-> (&rest Any) Any))
  (treesit-node-child . (-> (&rest Any) Any))
  (treesit-node-child-by-field-name . (-> (&rest Any) Any))
  (treesit-node-child-count . (-> (&rest Any) Any))
  (treesit-node-descendant-for-range . (-> (&rest Any) Any))
  (treesit-node-end . (-> (&rest Any) Any))
  (treesit-node-eq . (-> (&rest Any) Any))
  (treesit-node-field-name-for-child . (-> (&rest Any) Any))
  (treesit-node-first-child-for-pos . (-> (&rest Any) Any))
  (treesit-node-match-p . (-> (&rest Any) Any))
  (treesit-node-next-sibling . (-> (&rest Any) Any))
  (treesit-node-p . (-> (&rest Any) Any))
  (treesit-node-parent . (-> (&rest Any) Any))
  (treesit-node-parser . (-> (&rest Any) Any))
  (treesit-node-prev-sibling . (-> (&rest Any) Any))
  (treesit-node-start . (-> (&rest Any) Any))
  (treesit-node-string . (-> (&rest Any) Any))
  (treesit-node-type . (-> (&rest Any) Any))
  (treesit-parser-add-notifier . (-> (&rest Any) Any))
  (treesit-parser-buffer . (-> (&rest Any) Any))
  (treesit-parser-create . (-> (&rest Any) Any))
  (treesit-parser-delete . (-> (&rest Any) Any))
  (treesit-parser-included-ranges . (-> (&rest Any) Any))
  (treesit-parser-language . (-> (&rest Any) Any))
  (treesit-parser-list . (-> (&rest Any) Any))
  (treesit-parser-notifiers . (-> (&rest Any) Any))
  (treesit-parser-p . (-> (&rest Any) Any))
  (treesit-parser-remove-notifier . (-> (&rest Any) Any))
  (treesit-parser-root-node . (-> (&rest Any) Any))
  (treesit-parser-set-included-ranges . (-> (&rest Any) Any))
  (treesit-parser-tag . (-> (&rest Any) Any))
  (treesit-pattern-expand . (-> (&rest Any) Any))
  (treesit-query-capture . (-> (&rest Any) Any))
  (treesit-query-compile . (-> (&rest Any) Any))
  (treesit-query-expand . (-> (&rest Any) Any))
  (treesit-query-language . (-> (&rest Any) Any))
  (treesit-query-p . (-> (&rest Any) Any))
  (treesit-search-forward . (-> (&rest Any) Any))
  (treesit-search-subtree . (-> (&rest Any) Any))
  (treesit-subtree-stat . (-> (&rest Any) Any))
  (truncate . (-> (&rest Any) Any))
  (try-completion . (-> (&rest Any) Any))
  (tty-display-color-cells . (-> (&rest Any) Any))
  (tty-display-color-p . (-> (&rest Any) Any))
  (tty-no-underline . (-> (&rest Any) Any))
  (tty--output-buffer-size . (-> (&rest Any) Any))
  (tty--set-output-buffer-size . (-> (&rest Any) Any))
  (tty-suppress-bold-inverse-default-colors . (-> (&rest Any) Any))
  (tty-top-frame . (-> (&rest Any) Any))
  (tty-type . (-> (&rest Any) Any))
  (type-of . (-> (&rest Any) Any))
  (undo-boundary . (-> (&rest Any) Any))
  (unencodable-char-position . (-> (&rest Any) Any))
  (unhandled-file-name-directory . (-> (&rest Any) Any))
  (unibyte-char-to-multibyte . (-> (&rest Any) Any))
  (unibyte-string . (-> (&rest Any) Any))
  (unicode-property-table-internal . (-> (&rest Any) Any))
  (unify-charset . (-> (&rest Any) Any))
  (unintern . (-> (&rest Any) Any))
  (unix-sync . (-> (&rest Any) Any))
  (unlock-buffer . (-> (&rest Any) Any))
  (unlock-file . (-> (&rest Any) Any))
  (unwind-protect . (-> (&rest Any) Any))
  (upcase . (-> (&rest Any) Any))
  (upcase-initials . (-> (&rest Any) Any))
  (upcase-initials-region . (-> (&rest Any) Any))
  (upcase-region . (-> (&rest Any) Any))
  (upcase-word . (-> (&rest Any) Any))
  (use-global-map . (-> (&rest Any) Any))
  (use-local-map . (-> (&rest Any) Any))
  (user-full-name . (-> (&rest Any) Any))
  (user-login-name . (-> (&rest Any) Any))
  (user-ptrp . (-> (&rest Any) Any))
  (user-real-login-name . (-> (&rest Any) Any))
  (user-real-uid . (-> (&rest Any) Any))
  (user-uid . (-> (&rest Any) Any))
  (variable-binding-locus . (-> (&rest Any) Any))
  (vconcat . (-> (&rest Any) Any))
  (vector . (-> (&rest Any) Any))
  (vector-or-char-table-p . (-> (&rest Any) Any))
  (vectorp . (-> (&rest Any) Any))
  (verify-visited-file-modtime . (-> (&rest Any) Any))
  (vertical-motion . (-> (&rest Any) Any))
  (visible-frame-list . (-> (&rest Any) Any))
  (visited-file-modtime . (-> (&rest Any) Any))
  (w16-get-clipboard-data . (-> (&rest Any) Any))
  (w16-selection-exists-p . (-> (&rest Any) Any))
  (w16-set-clipboard-data . (-> (&rest Any) Any))
  (w32-application-type . (-> (&rest Any) Any))
  (w32-battery-status . (-> (&rest Any) Any))
  (w32-define-rgb-color . (-> (&rest Any) Any))
  (w32-display-monitor-attributes-list . (-> (&rest Any) Any))
  (w32-frame-edges . (-> (&rest Any) Any))
  (w32-frame-geometry . (-> (&rest Any) Any))
  (w32-frame-list-z-order . (-> (&rest Any) Any))
  (w32-frame-restack . (-> (&rest Any) Any))
  (w32-get-clipboard-data . (-> (&rest Any) Any))
  (w32-get-codepage-charset . (-> (&rest Any) Any))
  (w32-get-console-codepage . (-> (&rest Any) Any))
  (w32-get-console-output-codepage . (-> (&rest Any) Any))
  (w32-get-current-locale-id . (-> (&rest Any) Any))
  (w32-get-default-locale-id . (-> (&rest Any) Any))
  (w32-get-ime-open-status . (-> (&rest Any) Any))
  (w32-get-keyboard-layout . (-> (&rest Any) Any))
  (w32-get-locale-info . (-> (&rest Any) Any))
  (w32-get-valid-codepages . (-> (&rest Any) Any))
  (w32-get-valid-keyboard-layouts . (-> (&rest Any) Any))
  (w32-get-valid-locale-ids . (-> (&rest Any) Any))
  (w32-has-winsock . (-> (&rest Any) Any))
  (w32-long-file-name . (-> (&rest Any) Any))
  (w32--menu-bar-in-use . (-> (&rest Any) Any))
  (w32-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (w32-notification-close . (-> (&rest Any) Any))
  (w32-notification-notify . (-> (&rest Any) Any))
  (w32notify-add-watch . (-> (&rest Any) Any))
  (w32notify-rm-watch . (-> (&rest Any) Any))
  (w32notify-valid-p . (-> (&rest Any) Any))
  (w32-read-registry . (-> (&rest Any) Any))
  (w32-reconstruct-hot-key . (-> (&rest Any) Any))
  (w32-registered-hot-keys . (-> (&rest Any) Any))
  (w32-register-hot-key . (-> (&rest Any) Any))
  (w32-selection-exists-p . (-> (&rest Any) Any))
  (w32-selection-targets . (-> (&rest Any) Any))
  (w32-send-sys-command . (-> (&rest Any) Any))
  (w32-set-clipboard-data . (-> (&rest Any) Any))
  (w32-set-console-codepage . (-> (&rest Any) Any))
  (w32-set-console-output-codepage . (-> (&rest Any) Any))
  (w32-set-current-locale . (-> (&rest Any) Any))
  (w32-set-ime-open-status . (-> (&rest Any) Any))
  (w32-set-keyboard-layout . (-> (&rest Any) Any))
  (w32-set-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (w32-set-process-priority . (-> (&rest Any) Any))
  (w32-set-wallpaper . (-> (&rest Any) Any))
  (w32-shell-execute . (-> (&rest Any) Any))
  (w32-short-file-name . (-> (&rest Any) Any))
  (w32-toggle-lock-key . (-> (&rest Any) Any))
  (w32-unload-winsock . (-> (&rest Any) Any))
  (w32-unregister-hot-key . (-> (&rest Any) Any))
  (w32-window-exists-p . (-> (&rest Any) Any))
  (waiting-for-user-input-p . (-> (&rest Any) Any))
  (where-is-internal . (-> (&rest Any) Any))
  (while . (-> (&rest Any) Any))
  (widen . (-> (&rest Any) Any))
  (widget-apply . (-> (&rest Any) Any))
  (widget-get . (-> (&rest Any) Any))
  (widget-put . (-> (&rest Any) Any))
  (window-at . (-> (&rest Any) Any))
  (window-body-height . (-> (&rest Any) Any))
  (window-body-width . (-> (&rest Any) Any))
  (window-bottom-divider-width . (-> (&rest Any) Any))
  (window-buffer . (-> (&rest Any) Any))
  (window-bump-use-time . (-> (&rest Any) Any))
  (window-combination-limit . (-> (&rest Any) Any))
  (window-configuration-equal-p . (-> (&rest Any) Any))
  (window-configuration-frame . (-> (&rest Any) Any))
  (window-configuration-p . (-> (&rest Any) Any))
  (window-dedicated-p . (-> (&rest Any) Any))
  (window-display-table . (-> (&rest Any) Any))
  (window-end . (-> (&rest Any) Any))
  (window-frame . (-> (&rest Any) Any))
  (window-fringes . (-> (&rest Any) Any))
  (window-header-line-height . (-> (&rest Any) Any))
  (window-hscroll . (-> (&rest Any) Any))
  (window-left-child . (-> (&rest Any) Any))
  (window-left-column . (-> (&rest Any) Any))
  (window-line-height . (-> (&rest Any) Any))
  (window-lines-pixel-dimensions . (-> (&rest Any) Any))
  (window-list . (-> (&rest Any) Any))
  (window-list-1 . (-> (&rest Any) Any))
  (window-live-p . (-> (&rest Any) Any))
  (window-margins . (-> (&rest Any) Any))
  (window-minibuffer-p . (-> (&rest Any) Any))
  (window-mode-line-height . (-> (&rest Any) Any))
  (window-new-normal . (-> (&rest Any) Any))
  (window-new-pixel . (-> (&rest Any) Any))
  (window-new-total . (-> (&rest Any) Any))
  (window-next-buffers . (-> (&rest Any) Any))
  (window-next-sibling . (-> (&rest Any) Any))
  (window-normal-size . (-> (&rest Any) Any))
  (window-old-body-pixel-height . (-> (&rest Any) Any))
  (window-old-body-pixel-width . (-> (&rest Any) Any))
  (window-old-buffer . (-> (&rest Any) Any))
  (window-old-pixel-height . (-> (&rest Any) Any))
  (window-old-pixel-width . (-> (&rest Any) Any))
  (window-old-point . (-> (&rest Any) Any))
  (windowp . (-> (&rest Any) Any))
  (window-parameter . (-> (&rest Any) Any))
  (window-parameters . (-> (&rest Any) Any))
  (window-parent . (-> (&rest Any) Any))
  (window-pixel-height . (-> (&rest Any) Any))
  (window-pixel-left . (-> (&rest Any) Any))
  (window-pixel-top . (-> (&rest Any) Any))
  (window-pixel-width . (-> (&rest Any) Any))
  (window-point . (-> (&rest Any) Any))
  (window-prev-buffers . (-> (&rest Any) Any))
  (window-prev-sibling . (-> (&rest Any) Any))
  (window-resize-apply . (-> (&rest Any) Any))
  (window-resize-apply-total . (-> (&rest Any) Any))
  (window-right-divider-width . (-> (&rest Any) Any))
  (window-scroll-bar-height . (-> (&rest Any) Any))
  (window-scroll-bars . (-> (&rest Any) Any))
  (window-scroll-bar-width . (-> (&rest Any) Any))
  (window-start . (-> (&rest Any) Any))
  (window-system . (-> (&rest Any) Any))
  (window-tab-line-height . (-> (&rest Any) Any))
  (window-text-height . (-> (&rest Any) Any))
  (window-text-pixel-size . (-> (&rest Any) Any))
  (window-text-width . (-> (&rest Any) Any))
  (window-top-child . (-> (&rest Any) Any))
  (window-top-line . (-> (&rest Any) Any))
  (window-total-height . (-> (&rest Any) Any))
  (window-total-width . (-> (&rest Any) Any))
  (window-use-time . (-> (&rest Any) Any))
  (window-valid-p . (-> (&rest Any) Any))
  (window-vscroll . (-> (&rest Any) Any))
  (write-char . (-> (&rest Any) Any))
  (write-region . (-> (&rest Any) Any))
  (x-backspace-delete-keys-p . (-> (&rest Any) Any))
  (x-begin-drag . (-> (&rest Any) Any))
  (x-change-window-property . (-> (&rest Any) Any))
  (x-close-connection . (-> (&rest Any) Any))
  (x-create-frame . (-> (&rest Any) Any))
  (x-delete-window-property . (-> (&rest Any) Any))
  (x-disown-selection-internal . (-> (&rest Any) Any))
  (x-display-backing-store . (-> (&rest Any) Any))
  (x-display-color-cells . (-> (&rest Any) Any))
  (x-display-grayscale-p . (-> (&rest Any) Any))
  (x-display-list . (-> (&rest Any) Any))
  (x-display-mm-height . (-> (&rest Any) Any))
  (x-display-mm-width . (-> (&rest Any) Any))
  (x-display-monitor-attributes-list . (-> (&rest Any) Any))
  (x-display-pixel-height . (-> (&rest Any) Any))
  (x-display-pixel-width . (-> (&rest Any) Any))
  (x-display-planes . (-> (&rest Any) Any))
  (x-display-save-under . (-> (&rest Any) Any))
  (x-display-screens . (-> (&rest Any) Any))
  (x-display-set-last-user-time . (-> (&rest Any) Any))
  (x-display-visual-class . (-> (&rest Any) Any))
  (x-double-buffered-p . (-> (&rest Any) Any))
  (x-export-frames . (-> (&rest Any) Any))
  (x-family-fonts . (-> (&rest Any) Any))
  (x-file-dialog . (-> (&rest Any) Any))
  (x-focus-frame . (-> (&rest Any) Any))
  (x-frame-edges . (-> (&rest Any) Any))
  (x-frame-geometry . (-> (&rest Any) Any))
  (x-frame-list-z-order . (-> (&rest Any) Any))
  (x-frame-restack . (-> (&rest Any) Any))
  (x-get-atom-name . (-> (&rest Any) Any))
  (x-get-local-selection . (-> (&rest Any) Any))
  (x-get-modifier-masks . (-> (&rest Any) Any))
  (x-get-page-setup . (-> (&rest Any) Any))
  (x-get-resource . (-> (&rest Any) Any))
  (x-get-selection-internal . (-> (&rest Any) Any))
  (x-gtk-debug . (-> (&rest Any) Any))
  (x-hide-tip . (-> (&rest Any) Any))
  (x-internal-focus-input-context . (-> (&rest Any) Any))
  (x-list-fonts . (-> (&rest Any) Any))
  (x-load-color-file . (-> (&rest Any) Any))
  (x-menu-bar-open-internal . (-> (&rest Any) Any))
  (x-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (x-open-connection . (-> (&rest Any) Any))
  (x-own-selection-internal . (-> (&rest Any) Any))
  (x-page-setup-dialog . (-> (&rest Any) Any))
  (x-parse-geometry . (-> (&rest Any) Any))
  (x-popup-dialog . (-> (&rest Any) Any))
  (x-popup-menu . (-> (&rest Any) Any))
  (x-print-frames-dialog . (-> (&rest Any) Any))
  (x-register-dnd-atom . (-> (&rest Any) Any))
  (x-select-font . (-> (&rest Any) Any))
  (x-selection-exists-p . (-> (&rest Any) Any))
  (x-selection-owner-p . (-> (&rest Any) Any))
  (x-send-client-message . (-> (&rest Any) Any))
  (x-server-input-extension-version . (-> (&rest Any) Any))
  (x-server-max-request-size . (-> (&rest Any) Any))
  (x-server-vendor . (-> (&rest Any) Any))
  (x-server-version . (-> (&rest Any) Any))
  (x-set-mouse-absolute-pixel-position . (-> (&rest Any) Any))
  (x-show-tip . (-> (&rest Any) Any))
  (x-synchronize . (-> (&rest Any) Any))
  (x-test-string-conversion . (-> (&rest Any) Any))
  (x-translate-coordinates . (-> (&rest Any) Any))
  (x-uses-old-gtk-dialog . (-> (&rest Any) Any))
  (xw-color-defined-p . (-> (&rest Any) Any))
  (xw-color-values . (-> (&rest Any) Any))
  (xw-display-color-p . (-> (&rest Any) Any))
  (xwidget-buffer . (-> (&rest Any) Any))
  (xwidget-info . (-> (&rest Any) Any))
  (xwidget-live-p . (-> (&rest Any) Any))
  (xwidgetp . (-> (&rest Any) Any))
  (xwidget-perform-lispy-event . (-> (&rest Any) Any))
  (xwidget-plist . (-> (&rest Any) Any))
  (xwidget-query-on-exit-flag . (-> (&rest Any) Any))
  (xwidget-resize . (-> (&rest Any) Any))
  (xwidget-size-request . (-> (&rest Any) Any))
  (xwidget-view-info . (-> (&rest Any) Any))
  (xwidget-view-lookup . (-> (&rest Any) Any))
  (xwidget-view-model . (-> (&rest Any) Any))
  (xwidget-view-p . (-> (&rest Any) Any))
  (xwidget-view-window . (-> (&rest Any) Any))
  (xwidget-webkit-back-forward-list . (-> (&rest Any) Any))
  (xwidget-webkit-estimated-load-progress . (-> (&rest Any) Any))
  (xwidget-webkit-execute-script . (-> (&rest Any) Any))
  (xwidget-webkit-finish-search . (-> (&rest Any) Any))
  (xwidget-webkit-goto-history . (-> (&rest Any) Any))
  (xwidget-webkit-goto-uri . (-> (&rest Any) Any))
  (xwidget-webkit-load-html . (-> (&rest Any) Any))
  (xwidget-webkit-next-result . (-> (&rest Any) Any))
  (xwidget-webkit-previous-result . (-> (&rest Any) Any))
  (xwidget-webkit-search . (-> (&rest Any) Any))
  (xwidget-webkit-set-cookie-storage-file . (-> (&rest Any) Any))
  (xwidget-webkit-stop-loading . (-> (&rest Any) Any))
  (xwidget-webkit-title . (-> (&rest Any) Any))
  (xwidget-webkit-uri . (-> (&rest Any) Any))
  (xwidget-webkit-zoom . (-> (&rest Any) Any))
  (x-window-property . (-> (&rest Any) Any))
  (x-window-property-attributes . (-> (&rest Any) Any))
  (x-wm-set-size-hint . (-> (&rest Any) Any))
  (yes-or-no-p . (-> (&rest Any) Any))
  (zlib-available-p . (-> (&rest Any) Any))
  (zlib-decompress-region . (-> (&rest Any) Any)))

(Emil:Env:declare-variables)

(provide 'Emil/Builtin)
